Controllers/CourseController.cs
using EfcoreApp.Data;
using EfcoreApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EfcoreApp.Controllers;

public class CourseController : Controller
{
    private readonly DataContext _context;

    public CourseController(DataContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> Index()
    {
        var courses = await _context.Courses.Include(x=>x.Instructor).ToListAsync();
        return View(courses);
    }
    public async Task<IActionResult> Create()
    {
        ViewBag.Instructors = new SelectList(await _context.Instructors.ToListAsync(), "InstructorId", "NameSurname");
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CourseDTO model)
    {
        if(ModelState.IsValid)
        {        
        _context.Courses.Add(new Course() {CourseId = model.CourseId, Title = model.Title, InstructorId = model.InstructorId });
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
        }
        ViewBag.Instructors = new SelectList(await _context.Instructors.ToListAsync(), "InstructorId", "NameSurname");
        return View(model);
    }
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var course = await _context.Courses.Include(x=>x.CourseRegistrations).ThenInclude(x=>x.Student).Select(x=>  new CourseDTO {
            CourseId = x.CourseId, CourseRegistrations = x.CourseRegistrations, InstructorId = x.InstructorId, Title = x.Title
        }).FirstOrDefaultAsync(x => x.CourseId == id);
        if (course == null)
        {
            return NotFound();
        }
        ViewBag.Instructors = new SelectList(await _context.Instructors.ToListAsync(), "InstructorId", "NameSurname");
        return View(course);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int? id, CourseDTO model)
    {
        if (id != model.CourseId)
        {
            return NotFound();
        }
        if (ModelState.IsValid)
        {
            try
            {
                _context.Courses.Update(new Course() {CourseId = model.CourseId, Title = model.Title, InstructorId = model.InstructorId });
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Courses.Any(x => x.CourseId == model.CourseId))
                {
                    return NotFound();
                }
                throw;
            }
        }
        ViewBag.Instructors = new SelectList(await _context.Instructors.ToListAsync(), "InstructorId", "NameSurname");
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var course = await _context.Courses.FindAsync(id);

        if (course == null)
        {
            return NotFound();
        }
        return View(course);
    }

    [HttpPost]
    public async Task<IActionResult> Delete([FromForm] int id)
    {
        var course = await _context.Courses.FirstOrDefaultAsync(o => o.CourseId == id);

        if (course == null)
        {
            return NotFound();
        }
        try
        {
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!_context.Courses.Any(x => x.CourseId == course.CourseId))
            {
                return NotFound();
            }
            throw;
        }
    }
}

Controllers/CourseRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EfcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EfcoreApp.Controllers;

public class CourseRegistrationController: Controller
{
    private readonly DataContext _context;

    public CourseRegistrationController(DataContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var courseRegistrations = await _context.CourseRegistrations.Include(x=>x.Student).Include(x=>x.Course).ToListAsync();
        return View(courseRegistrations);
    }
    public async Task<IActionResult> Create()
    {
        ViewBag.Students = new SelectList(await _context.Students.ToListAsync(), "StudentId", "NameSurname");
        ViewBag.Courses = new SelectList(await _context.Courses.ToListAsync(), "CourseId", "Title");
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]     
    public async Task<IActionResult> Create(CourseRegistration model)
    {
        model.RegistrationDate = DateTime.Now;
        _context.CourseRegistrations.Add(model);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }     
}

Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EfcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EfcoreApp.Controllers
{
    public class InstructorController: Controller
    {
        private readonly DataContext _context;

        public InstructorController(DataContext context)
        {
            this._context = context;
        }


        public async Task<IActionResult> Index()
        {
            var instructors = await _context.Instructors.ToListAsync();
            return View(instructors);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Instructor model)
        {
            _context.Instructors.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit (int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var instructor = await _context.Instructors.Include(x=>x.Courses).FirstOrDefaultAsync(x=>x.InstructorId==id);
            
            if(instructor==null)
            {
                return NotFound();
            }
            return View(instructor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (int? id, Instructor model)
        {
            if(id!=model.InstructorId)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Instructors.Update(model);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Instructors.Any(x => x.InstructorId == model.InstructorId))
                    {
                        return NotFound();
                    }
                    throw;
                }

            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = await _context.Instructors.FirstOrDefaultAsync(o => o.InstructorId == id);

            if (entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var entity = await _context.Instructors.FirstOrDefaultAsync(o => o.InstructorId == id);

            if (entity == null)
            {
                return NotFound();
            }
            try
            {
                _context.Instructors.Remove(entity);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Instructors.Any(x => x.InstructorId == entity.InstructorId))
                {
                    return NotFound();
                }
                throw;
            }            
        }
    }
}

Controllers/StudentController.cs
using EfcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EfcoreApp.Controllers
{
    public class StudentController: Controller
    {
        private readonly DataContext _context;

        public StudentController(DataContext context)
        {
            _context = context;
        }
        // var context = new DataContext(); Bunu yazmaya gerek yok. Onun yerine constructor injection yapacağız.

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Student model)
        {
            _context.Students.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index()
        {
            var students = await _context.Students.ToListAsync();
            return View(students);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var entity = await _context.Students.FindAsync(id); //Alttaki ile aynı anlama gelir. Async metot async olduğu için.
            // FindAsync sade id içinken FinOrDefaultAsync ile her değişken aranabilir.
            // var entity = await _context.Students.FirstOrDefaultAsync(o => o.StudentId==id);
            
            if(entity==null)
            {
                return NotFound();
            }
            return View(entity);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]       
        public async Task<IActionResult> Edit(int? id, Student model)
        {
            if(id != model.StudentId)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Students.Update(model);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch(DbUpdateConcurrencyException)
                {
                    if(!_context.Students.Any(x=>x.StudentId == model.StudentId))
                    {
                        return NotFound();
                    }
                    throw;
                }
                    
            }
            return View(model);
        }       

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
    {
        if(id == null)
        {
            return NotFound();
        }
        var entity = await _context.Students.FirstOrDefaultAsync(o => o.StudentId==id);
        
        if(entity==null)
        {
            return NotFound();
        }
        return View(entity);
    }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfcoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EfcoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfcoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CourseRegistration" asp-action="Index">Course Registrations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EfcoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>